// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwepfribozwhpzwlpiuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZXBmcmlib3p3aHB6d2xwaXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDAxMDIsImV4cCI6MjA2NDYxNjEwMn0.GG24EBS27xXPY9iva1_P7CNrOL_1lhsUmtign5IWwTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);